### ISSUE TITLE
The example doesn't work

### ISSUE THREAD

**Issue by rajdee** [rasmusfl0e/posthtml-static-react#5]
The example is not working. I suppose what you forgot about jsx transformation.

**Comment by phloe** [comment]
No I didn't :D 
...I had just figured that people using React wouldn't think twice about having to add the transformation.

But - yes - it was a contrived example having a static React component inside the example script code. Require'ing the component from a separate file would yield the same problems though... still needs transformation.

I'll make a note in the readme about the missing transformation step - and possible solution.
